#! /bin/bash

java -jar ../tools/compiler.jar --js sifobject.js --js Layer.js --js PasteCanvas.js --js region.js --js translate.js --js rotate.js --js zoom.js --js import.js --js restore.js --js_output_file ../build/sifplayer.min.js
